// Scratch: build translations.es.json for L2 (inline high-fidelity ES, glossary-locked).
const fs = require('fs');
const path = require('path');
const T = [
[0, `Meditación de las Rosas`],
[1, `Portada de Meditación de las Rosas Nivel 2`],
[2, `<p style="text-align:center"><em>Prácticas avanzadas para la conciencia del cuerpo sutil, la alquimia emocional y la coherencia relacional.</em></p>`],
[3, `Índice`],
[4, `<ul><li>Preparando Tu Espacio Físico</li><li>Limpieza del Espacio</li><li>Apropiarte de Tu Espacio</li><li>Hablemos de los Chakras</li><li>Los Siete Chakras</li><li>Limpieza de Cada Chakra</li><li>Limpieza de Cada Capa del Aura</li><li>La Rosa de Recuperación de Energía en Profundidad</li><li>Rosas Doradas Adhesivas</li><li>Rosas Doradas Adhesivas (continuación)</li><li>Elementos de la Meditación de las Rosas — Nivel 2</li></ul>`],
[5, `<p><em>Nivel 2 — Práctica Profunda</em></p>`],
[6, `Preparando Tu Espacio Físico`],
[7, `Protección del Espacio`],
[8, `<ul><li>Crea 4 Rosas Doradas, cada una con un tallo dorado y enraizada.</li><li>Crea 4 líneas doradas desde las cuatro esquinas superiores de la habitación, uniéndose en el centro del techo.</li><li>Crea 4 líneas doradas desde las cuatro esquinas inferiores, uniéndose en el centro del suelo.</li><li>Crea una línea dorada desde el punto superior hasta el punto inferior, unificando la energía.</li><li>Desde el centro del suelo, donde se encuentran las 4 líneas, crea un cordón de enraizamiento transparente hacia el centro de la Tierra y expándelo hasta los bordes de la habitación.</li><li>Observa toda la habitación vibrando en dorado.</li></ul>`],
[9, `<p>Antes de meditar, prepara tu entorno físico para sostener el trabajo energético. El espacio externo debe reflejar la intención interna: limpio, despejado, silencioso y sostenido con intención.</p>`],
[10, `<p>Protección del Espacio</p>`],
[11, `<p>Ahora prepara la habitación en la que te encuentras para que esté limpia y protegida:</p>`],
[12, `Limpieza del Espacio`],
[13, `Autoridad Energética`],
[14, `Observaciones Importantes`],
[15, `Limpieza del Espacio`],
[16, `Apropiarte de Tu Espacio`],
[17, `Limpieza del Espacio`],
[18, `Apropiarte de Tu Espacio`],
[19, `<ul><li>Crea 4 líneas doradas desde el chakra corona hasta las 4 esquinas superiores de la habitación.</li><li>Crea 4 líneas doradas desde el chakra raíz hasta las cuatro esquinas inferiores de la habitación.</li><li>Si meditas en un espacio al aire libre, crea una cúpula o una habitación dorada a tu alrededor y realiza todas las técnicas como si estuvieras en un espacio cerrado.</li></ul>`],
[20, `<p>Una vez establecida la protección, sigue la limpieza. Se coloca una Rosa Dorada sobre la rejilla y se hace descender a través de toda su estructura, retirando cualquier energía ajena, estancada o perturbadora dentro de la habitación. Esta Rosa desciende para ser transmutada en el centro de la tierra a través del Cordón de Enraizamiento de la habitación.</p>`],
[21, `<p>Apropíate de la habitación para tener autoridad sobre el espacio donde estás meditando:</p>`],
[22, `<p>Si estás meditando en un espacio que no está bajo tu autoridad energética, limita tu protección al área inmediata a tu alrededor y luego, al finalizar, explota las cuatro Rosas Doradas hacia afuera. Si el espacio es tuyo &mdash; o se encuentra dentro de tu autoridad energética &mdash; las cuatro Rosas Doradas pueden permanecer, continuando sosteniéndolo y protegiéndolo.</p>`],
[23, `Referencia`],
[24, `Hablemos de los Chakras`],
[25, `Los Siete Chakras`],
[26, `Introducción a los Chakras`],
[27, `<p>El sistema de chakras es la anatomía energética del cuerpo humano. Existen siete chakras principales, cada uno rige aspectos específicos de la vida física, emocional, mental y espiritual.</p>`],
[28, `Los Chakras Individuales`],
[29, `Chakra Raíz`],
[30, `Chakra Sacro`],
[31, `<ul><li>Presencia enraizada</li><li>Vitalidad física</li><li>Confianza en la vida</li><li>Sentirse seguro en el cuerpo</li></ul>`],
[32, `<ul><li>Miedo e inseguridad</li><li>Ansiedad de supervivencia</li><li>Desconexión del cuerpo</li><li>Mentalidad de escasez</li></ul>`],
[33, `<ul><li>Bienestar emocional</li><li>Sensualidad e intimidad</li><li>Pasión y placer</li><li>Adaptabilidad</li></ul>`],
[34, `<ul><li>Depresión y entumecimiento</li><li>Disfunción sexual</li><li>Inestabilidad emocional</li><li>Miedo al cambio</li></ul>`],
[35, `<p><strong>Bloqueos:</strong> Miedo — Inseguridad — Trauma de Supervivencia</p>`],
[36, `<p><strong>Bloqueos:</strong> Vergüenza — Represión Emocional — Culpa</p>`],
[37, `Chakra del Plexo Solar`],
[38, `Chakra Corazón`],
[39, `<ul><li>Confianza y motivación</li><li>Responsable y disciplinado</li><li>Sentido saludable de sí mismo</li><li>Autonomía</li></ul>`],
[40, `<ul><li>Baja autoestima</li><li>Agresividad o control</li><li>Terquedad y dominación</li><li>Falta de dirección o propósito</li></ul>`],
[41, `<ul><li>Compasión y empatía</li><li>Apertura emocional</li><li>Perdón</li><li>Intimidad saludable y amor propio</li></ul>`],
[42, `<ul><li>Retraimiento emocional o entrega excesiva</li><li>Miedo a la intimidad</li><li>Frialdad o desapego</li><li>Dificultad para perdonar</li></ul>`],
[43, `<p><em><span style="color: #4CAF50;">Verde — Amor Humano</span> — "YO AMO" — Amor condicional, empatía, perdón, relaciones saludables.</em></p>`],
[44, `<p><em><span style="color: #D4669A;">Rosa — Amor Divino</span> — "YO SOY AMOR" — Amor incondicional, compasión, interconexión, amor divino y universal.</em></p>`],
[45, `<p><strong>Bloqueos:</strong> Dudas sobre Uno Mismo — Inseguridad — Miedo al Rechazo</p>`],
[46, `<p><strong>Bloqueos:</strong> Duelo — Traición — Desamor</p>`],
[47, `Chakra Garganta`],
[48, `Chakra del Tercer Ojo`],
[49, `<ul><li>Comunicación clara y honesta</li><li>Expresión auténtica de sí mismo</li><li>Buen oyente</li><li>Voz firme y habla equilibrada</li></ul>`],
[50, `<ul><li>Miedo a hablar</li><li>Sentirse no escuchado o malinterpretado</li><li>Complacencia con los demás</li><li>Sentimientos reprimidos o mentiras</li></ul>`],
[51, `<ul><li>Visión clara e intuición</li><li>Buena memoria e imaginación</li><li>Ubicación interior</li><li>Sabiduría y visión</li></ul>`],
[52, `<ul><li>Pensamiento excesivo</li><li>Niebla mental</li><li>Desconexión de la guía interior</li><li>Evasión de la realidad o bypass espiritual</li></ul>`],
[53, `<p><strong>Bloqueos:</strong> Verdad Reprimida — Miedo a la Expresión — Falta de Comunicación</p>`],
[54, `<p><strong>Bloqueos:</strong> Ilusión — Miedo a Ver — Rigidez Mental</p>`],
[55, `Chakra Corona`],
[56, `<p><em>Ahora que comprendes cada chakra, aprenderás a limpiarlos individualmente — comenzando por las capas del aura, luego cada chakra y, finalmente, una recuperación completa de energía.</em></p>`],
[57, `<p><strong>Bloqueos:</strong> Desconexión — Cinismo — Pérdida de Sentido</p>`],
[58, `Limpieza de Cada Chakra`],
[59, `Limpieza de Chakras`],
[60, `<ul><li>En el exterior del Aura, crea dos rosas enraizadas (en el color del chakra), una detrás de ti y una delante, a la altura del chakra. La Rosa delantera limpia las energías del presente; la Rosa trasera limpia las energías del pasado.</li><li>Crea y explota varias Rosas para limpiar el chakra en profundidad.</li><li>Crea una rosa sin raíz (en el color del chakra) para limpiar la capa del Aura correspondiente a la altura del chakra.</li><li>Crea y explota varias Rosas para limpiar las capas del Aura.</li><li>Crea una rosa enraizada a la altura del chakra fuera del Aura para absorber toda tu energía dispersa en esa vibración. Explótala — tu energía regresa elevada y purificada.</li></ul>`],
[61, `<p><em>Este procedimiento debe realizarse de igual manera para todos los chakras, comenzando por el primero y ascendiendo en orden hasta el séptimo.</em></p>`],
[62, `<p>Cada chakra individual se limpia utilizando rosas. Las rosas abordan dos dimensiones: <em>Dinámicas del Pasado</em> — patrones energéticos, huellas y bloqueos arrastrados de experiencias pasadas, y <em>Dinámicas del Presente</em> — influencias energéticas actuales, relaciones y situaciones que afectan al chakra.</p>`],
[63, `Limpieza de las Capas del Aura`],
[64, `Las Siete Capas del Aura`],
[65, `Limpieza de Cada Capa del Aura`],
[66, `Limpieza de Cada Capa del Aura`],
[67, `<ol><li>1.ª capa del Aura — Raíz</li><li>2.ª capa del Aura — Sacro</li><li>3.ª capa del Aura — Plexo Solar</li><li>4.ª capa del Aura — Corazón</li><li>5.ª capa del Aura — Garganta</li><li>6.ª capa del Aura — Tercer Ojo</li><li>7.ª capa del Aura — Corona</li></ol>`],
[68, `<p><em>Limpia cada capa del aura utilizando una rosa sin raíz en el color del chakra correspondiente. Crea y explota varias rosas para cada capa, trabajando desde la 1.ª capa hasta la 7.ª.</em></p>`],
[69, `<p>El aura está compuesta por siete capas, cada una correspondiente a un chakra. En el Nivel 2, cada capa se limpia individualmente desde la 1.ª hasta la 7.ª capa.</p>`],
[70, `Recuperación`],
[71, `La Rosa de Recuperación de Energía en Profundidad`],
[72, `Rosa de Recuperación de Energía`],
[73, `<p>Una vez completada la limpieza del chakra y su capa del aura correspondiente, el proceso de recuperación de energía puede desplegarse en su vibración, si te sientes llamado a hacerlo. Se puede crear una Rosa de recuperación sintonizada con esa frecuencia específica, atrayendo tu energía de regreso y restaurándola en ese mismo nivel. Puedes hacerlo desde el 1.er hasta el 7.º chakra.</p>`],
[74, `Limpieza Profunda`],
[75, `Rosas Doradas Adhesivas`],
[76, `Rosa Dorada Adhesiva — Primera Rosa: de la Corona a la Raíz`],
[77, `Rosa Dorada Adhesiva — Segunda Rosa: Brazos`],
[78, `<p>Se utilizan cuatro Rosas Doradas Adhesivas para una limpieza energética profunda del Aura, extrayendo cualquier energía ajena que aún permanezca después de la limpieza anterior.</p>`],
[79, `<p>Primera Rosa — de la Corona a la Raíz</p>`],
[80, `<p>La primera entra por el chakra corona, limpiando cada chakra en sucesión hasta la raíz.</p>`],
[81, `<p>Segunda Rosa — Brazos</p>`],
[82, `<p>La segunda desciende hasta el chakra garganta, donde se divide en dos Rosas que recorren los canales de los brazos, saliendo por los chakras de las manos.</p>`],
[83, `Limpieza Profunda`],
[84, `Rosas Doradas Adhesivas (continuación)`],
[85, `Rosa Dorada Adhesiva — Tercera Rosa: Piernas`],
[86, `Rosa Dorada Adhesiva — Cuarta Rosa: Aura Completa`],
[87, `<p><em>Al finalizar, las cuatro o bien explotan fuera del Aura o salen a través del cordón de enraizamiento, transmutando consigo las energías recogidas.</em></p>`],
[88, `<p>Tercera Rosa — Piernas</p>`],
[89, `<p>La tercera desciende hasta el chakra raíz, donde se convierte en dos Rosas que siguen los canales de las piernas, saliendo por los chakras de los pies.</p>`],
[90, `<p>Cuarta Rosa — Aura Completa</p>`],
[91, `<p>La cuarta abarca todo el ancho del Aura, descendiendo a través de todo el campo energético.</p>`],
[92, `Elementos de la Meditación de las Rosas — Nivel 2`],
[93, `Preparación del Espacio`],
[94, `Los Siete Chakras`],
[95, `Limpieza de Chakras y Aura`],
[96, `Rosas Doradas Adhesivas`],
[97, `Elementos de la Meditación de las Rosas Nivel 2`],
[98, `<ul><li>Preparar y proteger la habitación</li><li>Limpiar el espacio con una rosa dorada</li><li>Apropiarse del espacio (corona + raíz hacia las esquinas)</li><li>Cúpula dorada para espacios públicos</li></ul>`],
[99, `<ul><li>Raíz, Sacro, Plexo Solar, Corazón</li><li>Garganta, Tercer Ojo, Corona</li></ul>`],
[100, `<ul><li>Limpiar cada capa del aura (7 capas)</li><li>Limpiar cada chakra (rosas delantera + trasera)</li><li>Rosa de recuperación por chakra</li></ul>`],
[101, `<ul><li>Primera Rosa — de la Corona a la Raíz</li><li>Segunda Rosa — Brazos</li><li>Tercera Rosa — Piernas</li><li>Cuarta Rosa — Aura Completa</li></ul>`],
[102, `<p><em>¡SÍ! ¡AHORA ESTÁS LISTO PARA UN HERMOSO DÍA!</em></p>`],
];
const out = T.map(([idx, text]) => ({ idx, text }));
const dir = path.join(__dirname, '..', '_qie-output', 'roses-os', 'translation', 'rose-meditation-level-2-en');
fs.writeFileSync(path.join(dir, 'translations.es.json'), JSON.stringify(out, null, 2), 'utf-8');
console.log(`wrote translations.es.json with ${out.length} entries (idx 0..${out.length - 1})`);
