-- Migration 0002: widen manual_blocks.block_type CHECK constraint.
--
-- Authority: spec 001-richer-block-editor T-007 + AC3.
--
-- The current CHECK at manuals-schema.sql:79 lists the original six block types
-- but the TypeScript BlockType union has carried `image-row` for some time
-- without the constraint being widened. This migration:
--   (1) BACK-FIX: adds `image-row` to the CHECK list (currently a silent insert
--       hazard).
--   (2) FORWARD: adds every v2 variant from M3 so the TS code can reference them
--       BEFORE any code change ships (CHECK FIRST sequencing per Winston).
--
-- Re-runnable: drops the existing constraint by name if present, recreates.

-- Drop the existing CHECK constraint (named auto-generated by Postgres);
-- locate it by searching for a CHECK on manual_blocks.block_type then drop.
DO $$
DECLARE
  con_name TEXT;
BEGIN
  SELECT conname INTO con_name
  FROM pg_constraint
  WHERE conrelid = 'public.manual_blocks'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) ILIKE '%block_type%';

  IF con_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.manual_blocks DROP CONSTRAINT %I', con_name);
  END IF;
END $$;

-- Add the widened constraint with a stable name.
ALTER TABLE public.manual_blocks
  ADD CONSTRAINT manual_blocks_block_type_check
  CHECK (block_type IN (
    -- v1 (original six)
    'heading',
    'text',
    'image',
    'divider',
    'page-break',
    -- v1 (back-fix; was in TS union but not in CHECK)
    'image-row',
    -- v2 (spec 001-richer-block-editor M3 variants)
    'cover',
    'callout',
    'quote',
    'numbered-exercise',
    'captioned-figure',
    'spoken-instruction',
    'table',
    'footnote',
    'glossary',
    'section',
    'two-column-section'
  ));

-- Verification: ensure the CHECK is in place and the names are queryable.
-- Operator can confirm with:
--   SELECT pg_get_constraintdef(oid)
--   FROM pg_constraint
--   WHERE conname = 'manual_blocks_block_type_check';

-- ROLLBACK (run-only on operator request):
-- BEGIN;
--   ALTER TABLE public.manual_blocks DROP CONSTRAINT manual_blocks_block_type_check;
--   ALTER TABLE public.manual_blocks
--     ADD CONSTRAINT manual_blocks_block_type_check
--     CHECK (block_type IN ('heading','text','image','divider','page-break'));
-- COMMIT;
